#!/usr/bin/python3
"""
transmit lora to and from websocket of master server raspestrio
"""
import sys
import signal
import argparse
from pathlib import Path

import wsHelp as ws
import rw
import loraHelp as lora


# register a signal handler so when clean up the socket on ^C for instance
def handler(signum,_):
    """ Handle signals by closing the socket """
    if signum == signal.SIGINT:
        lora.close_sock()
    sys.exit(1)

signal.signal(signal.SIGALRM, handler)
signal.signal(signal.SIGINT, handler)

parser = argparse.ArgumentParser(description="Receive data from the e32 socket")
parser.add_argument('--datasock',
    help="data socket to send data to the e32",
    default="/run/e32.data")
parser.add_argument('--clientsock',
    help="client socket for e32 to send data this program",
    default=str(Path.home())+"/e32.rx.data")

args = parser.parse_args()

try:
    rw.setRW(True)
    lora.initSocks( args.clientsock,args.datasock)
finally:
    rw.setRW(False)

#################
# Core Logic

tv = True
def processLoraMsg(msg):
    global tv
    print("[lora] received : ", msg)
    lora.sendAck(msg)
    tv = not tv
    # ws.sendToWs({'type':'isAgendaDisabled','value':tv})


def setAgendaDisabled(b):
    print('agenda is ','disabled' if b else 'enabled')

def processWSMsg(msgStr):
    print("got ws",msgStr)


    if not 'type' in msg or not 'data' in msg :
        print('invalid type')
        return
    t=msg['type']
    d=msg['data']

    if t == "isAgendaDisabled":
        setAgendaDisabled(d)

def askState():
    ws.sendToWs({'type':'req','value':'isAgendaDisabled'})

askState()
while True:
    lora.handleLora(processLoraMsg)
    ws.handleWs(processWSMsg)
    # print ("loop")
    

